### ISSUE TITLE
Allow user-specified initial sample

### ISSUE THREAD

**Issue by carolyner** [carolyner/imabc#48]
The code currently allows either an LHS or uniform sample from priors at first run. Modify the code to allow the user to provide an initial sample of parameter values. This would allow model updating that builds from prior calculations when either i) new targets are added or ii) when the model is modified, but prior calibration results provide information about the joint distribution of parameters for the revised model.

**Comment by cmaerzluft** [comment]
@carolyner,

Here are my thoughts on doing this:
1) We will change previous_results_dir/tag to be something like starting_prior_sample where the user can pass either a file path to previous results or a data.frame with the initial sample of parameter values.
  a) If a file path is passed, the algorithm would mostly work as it does now. The only difference is that a user could also pass a targets object that may or may not have targets not previously examined (they would need a new target function that outputs the results for all the targets new and old correctly). Imabc would recalculate the targets and distances to make sure there are good values to continue from.
  b) if a data.frame is passed, the algorithm will assume it is a data.frame of parameter values for the first run. In this case, the algorithm would work the same way as a first run, but instead of generating the initial sample with LHS it would just use the data.frame provided. 

I think method b is all you are suggesting in your comment, but I think adding method a will be valuable as well. If you want to add parameters, you would have to do option b since you wouldn't have the Mean Covariance information from previous runs for newly added parameters. If you just want to add targets though, method a would allow you to use the Mean Covariance information calculated in the previous run. 

Does that make sense and am I think about it the way you are?

**Comment by pedroliman** [comment]
@ncollier, any thoughts about how we can implement this in a way that
requires minimal re-structuring of the workflow code?

The intent of this is to allow the user to specify an arbitrary initial
sample (a data.frame with one row per parameter vector and one column per
parameter) to start from. This allows sequential calibration runs with
arbitrary new parameters and targets. We will be using this approach to
perform our calibrations sequentially reducing the need to start from
scratch in every new calibration.

We can talk about this on our meeting tomorrow.

**Comment by carolyner** [comment]
Chris: It sounds like we are on the same page.

Yes, I was proposing just method b, as this is our current priority to allow sequential calibration.  I was not suggesting that necessarily passing the information as data.frame, I'm not sure of the best approach.

I agree that method a would be valuable too, as it would allow us to add targets without changes to the model structure. You are correct, the at this would mean first evaluating the current good parameters to see if the model predicts the new target within staring bounds.  I did not mention it because it is lower priority compared to sequential calibration.

**Comment by pedroliman** [comment]
Talking to Nick, it seems it makes sense to us to have a new imabc parameter that would accept the data.frame as an input. If we really wanted to, we could use the same parameter for a path and the parameters data.frame, but we don't think it is the best approach.

**Comment by carolyner** [comment]
note that this version of the "warm start" would require the passed parameters to represent an iid sample from the prior distribution, meaning they have equal probability of selection from the prior distribution.  Prior ranges would be passed via the "priors" file, which is still required and in this case all priors should be specified as uniform distributions. Incorporating weights at a warm start is more involved as it would require modification to the get_mix_dist code.

**Comment by cmaerzluft** [comment]
@cmaerzluft pushed to dev
